version: '2'
config:
  slack_notify: true
  slack_channel: video-anomal-detection-service
environment:
  BUILD_IMAGE: image-comparision
jobs:
  build_docker:
    steps:
      - build_image
  publish_docker:
    steps:
      - push_image
  deploy_dev:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: app-platform
          workload: video-anomaly-detection-worker
          spinnaker_pipeline: generic-v2
          deployment_config: dev-worker
  deploy_prod:
    steps:
      - deploy_production:
          cluster: k8s-app-platform-prod
          namespace: default
          workload: video-anomaly-detection-worker
          spinnaker_pipeline: generic-v2
          deployment_config: prod-worker
workflows:
  jenkins_pipeline:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - dev
                - master
      - publish_docker:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - dev
                - master
      - deploy_dev:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - dev
      - deploy_prod:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - master
deployment_config:
  dev-worker:
      ingress:
          enabled: false
  prod-worker:
      ingress:
          enabled: false